name: Maven Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    name: Build and Test Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B clean package --file pom.xml

      - name: Run Maven Tests
        run: mvn -B test --file pom.xml

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: target/*.jar

  upload:
    name: Upload Artifact
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: 1stPerson2DRenderer
          path: target/1stPerson2DRenderer-1.0.0-jar-with-dependencies.jar
